# Generated by Django 5.2.15 on 2026-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='locked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
